default_twitter: &default_twitter
  twitter_api_key: 'V67A4NILVROmcgeGlAlVK97lE'
  twitter_api_secret: 'jsf5On7Ux6faPlrl8YqUBIrAC7FTwHjfoJ7HBTV3FIrJ9nE8zj'

development:
  secret_key_base: 7445737d3a1e0685eff7196e9c0e45a6ef656d7ef0ae648623feb128eeb908d2d30ea16651c1e5e2227852d1797c2ce2236867d6dd2a24e3d24b004c592395bf
  <<: *default_twitter

test:
  secret_key_base: 83871b33e5c4dc7e80e6d0d4be1d4e27b92f10567c3b8844a289205f7798272fcd462c9af7337bdeebeda1d93cae95991af7daf3b2a698116a65bcb6ad5dbe6f
  <<: *default_twitter

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>